config/routes.rb
Rails.application.routes.draw do
  
  resources :resources do
    member do
      get 'users'
      get 'groups'
    end
  end
  
  resources :groups do
    member do
      get 'users'
      get 'resources'
      get 'subgroups'
    end
  end

  resources :users do
    member do
      get 'resources'
      get 'can_access'
      get 'is_member'
      get 'groups'
    end
  end

  resource :graph do
    post    'links' => 'graphs#create_link'
    delete  'links' => 'graphs#destroy_link'
    get     'api'   => 'graphs#api'
  end
    

  # You can have the root of your site routed with "root"
  root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/group.rb
class Group 
  include Neo4j::ActiveNode
  include Neo4j::Timestamps
  
  property :name, type: String
  property :description, type: String

  has_many :out, :children, type: :group, model_class: Group
  has_many :out, :resources, type: :resource

  def users(deep = false)
    session = Neo4j::Session.current
    result = session.query.match("(u:User)-[#{deep ? '*' : ''}]-({uuid: \"#{id}\"}) return u").to_a.uniq
    result.map{|item| item.u}
  end
  
  def all_resources(depth = nil)
    depth_str = depth ? "*1..#{depth}" : '*'
    session = Neo4j::Session.current
    result = session.query.match("({uuid: \"#{id}\"})-[#{depth_str}]-(r:Resource) return r").to_a.uniq
    result.map{|item| item.r}
  end
  
  def all_children(depth = nil)
    depth_str = depth ? "*1..#{depth}" : '*'
    session = Neo4j::Session.current
    result = session.query.match("({uuid: \"#{id}\"})-[#{depth_str}]->(g:Group) return g").to_a.uniq
    result.map{|item| item.g}
  end
  
  def connect_to(target)
    if target.class == Resource
      resources << target
    elsif target.class == Group
      children << target
    elsif target.class == User
      target.groups << self
    end
    true
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy, :users]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /group/1/users
  def users
    users = @group.users params[:deep]
    respond_to do |format|
      respond_to.json {render json: users}
    end
  end
  # GET /group/1/resources
   def resources
    resources = @group.resources
    respond_to do |format|
      respond_to.json {render json: resources}
    end
  end

   def subgroups
    subgroups = @group.all_children
    respond_to do |format|
      respond_to.json {render json: subgroups}
    end
  end
  
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :description)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, :class => 'form-control'  %>
  </div>
  <div class="form-group text-right">
    <%= f.submit :class => 'btn btn-primary btn-flat'  %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>User Group<small>Version 1.0</small></h1>
  <ol class="breadcrumb">
	<li><a href="#"><i class="fa fa-users"></i> Home</a></li>
	<li>Users</li>
  </ol>
</section>

<!-- Main content -->
<section class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-6">
				<div class="box">
		            <div class="box-header">
    	              <h3 class="box-title">Group information</h3>
		            </div>
		            <!-- /.box-header -->
		            <div class="box-body">
                        <%= render 'form' %>
                    </div>
			        <!-- /.box-body -->
			     </div>
			     <!-- /.box -->
			</div>
		</div>
    </div>
</section>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<!-- Content Header (Page header) -->
			<section class="content-header">
			  <h1>User Groups<small>Version 1.0</small></h1>
			  <ol class="breadcrumb">
				<li><a href="#"><i class="fa fa-users"></i> Home</a></li>
				<li>User Groups</li>
			  </ol>
			</section>

		<!-- Main content -->
		<section class="content">
			<div class="container-fluid">

<p id="notice"><%= notice %></p>

<div class="row">
					<div class="col-md-12">
						<div class="box">
			            <div class="box-header">
			              <h3 class="box-title">Active User Groups</h3>
                    <%= link_to 'New Group', new_group_path, :class => "btn btn-success btn-flat pull-right" %>
			            </div>
			            <!-- /.box-header -->
			            <div class="box-body table-responsive">
			              <table id="userGroupsTable" class="table table-bordered table-striped">
			                <thead>
			                <tr>
			                  <th>Name</th>
			                  <th>Descripton</th>
			                  <th class="width25px"></th>
			                </tr>
			                </thead>
			                <tbody>
			                  
			                   <% @groups.each do |group| %>
                          <tr>
                            <td><%= group.name %></td>
                            <td><%= group.description %></td>
                            <td><%= link_to 'Show', group %> <%= link_to 'Edit', edit_group_path(group) %> <%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                          </tr>
                        <% end %>
			                </tbody>
			              </table>
			            </div>
			            <!-- /.box-body -->
			          </div>
			          <!-- /.box -->
					</div>
				</div>
</div>
		</section>

app/views/groups/new.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>User Group<small>Version 1.0</small></h1>
  <ol class="breadcrumb">
	<li><a href="#"><i class="fa fa-users"></i> Home</a></li>
	<li>Users</li>
  </ol>
</section>

		<!-- Main content -->
<section class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-6">
				<div class="box">
		            <div class="box-header">
			              <h3 class="box-title">Group information</h3>
		            </div>
		            <!-- /.box-header -->
		            <div class="box-body">
                        <%= render 'form' %>
                    </div>
			            <!-- /.box-body -->
  	            </div>
	          <!-- /.box -->
			</div>
		</div>
<!-- <%= link_to 'Back', groups_path %> -->
	</div>
</section>
		

app/views/groups/show.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>User Group<small>Version 1.0</small></h1>
  <ol class="breadcrumb">
	<li><a href="#"><i class="fa fa-users"></i> Home</a></li>
	<li>User Group</li>
  </ol>
</section>

<!-- Main content -->
<section class="content">
	<div class="container-fluid">
	  <p id="notice"><%= notice %></p>
		<div class="row">
			<div class="col-lg-6">
				<div class="box">
		      <div class="box-header">
    	      <h3 class="box-title">Group information</h3>
		      </div>
		      <!-- /.box-header -->
		      <div class="box-body">
            <p>
              <strong>Name:</strong>
              <%= @group.name %>
            </p>
            <p>
              <strong>Description:</strong>
                <%= @group.description %>
            </p>  
          </div>
			    <!-- /.box-body -->
			   </div>
			   <!-- /.box -->
		  </div>
	  </div>
  </div>
</section>


<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>