config/routes.rb
Rails.application.routes.draw do
  
  resources :resources do
    member do
      get 'users'
      get 'groups'
    end
  end
  
  resources :groups do
    member do
      get 'users'
      get 'resources'
      get 'subgroups'
    end
  end

  resources :users do
    member do
      get 'resources'
      get 'can_access'
      get 'is_member'
      get 'groups'
    end
  end

  resource :graph do
    post    'links' => 'graphs#create_link'
    delete  'links' => 'graphs#destroy_link'
    get     'api'   => 'graphs#api'
  end
    

  # You can have the root of your site routed with "root"
  root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :full_path %><br>
    <%= f.text_field :full_path, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit :class => "btn btn-primary btn-flat" %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>Resource<small>Version 1.0</small></h1>
  <ol class="breadcrumb">
	<li><a href="#"><i class="fa fa-database"></i> Home</a></li>
	<li>Resource</li>
  </ol>
</section>

<!-- Main content -->
<section class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-6">
				<div class="box">
		            <div class="box-header">
    	              <h3 class="box-title">Editing Resource</h3>
		            </div>
		            <!-- /.box-header -->
		            <div class="box-body">
                        <%= render 'form' %>
                    </div>
			        <!-- /.box-body -->
			     </div>
			     <!-- /.box -->
			</div>
		</div>
    </div>
</section>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>Resources<small>Version 1.0</small></h1>
	<ol class="breadcrumb">
	  <li><a href="index.html"><i class="fa fa-database"></i> Home</a></li>
		<li>Resources</li>
	</ol>
</section>

<!-- Main content -->
<section class="content">
  <div class="container-fluid">
    <p id="notice"><%= notice %></p>
		<div class="row">
			<div class="col-md-12">
				<div class="box">
	        <div class="box-header">
		        <h3 class="box-title">All Resources</h3>
            <%= link_to 'New Resource', new_resource_path, :class => "pull-right btn btn-flat btn-success" %>
			    </div>
			    <!-- /.box-header -->
		      <div class="box-body">
		      	<div class="table-responsive">
		      		<table id="resourcesTable" class="table table-bordered table-striped">
		            <thead>
			            <tr>
			              <th>Name</th>
			              <th>Full Path</th>
			              <th>Description</th>
			              <th class="width25px"></th>
			            </tr>
			          </thead>
			          <tbody>
                <% @resources.each do |resource| %>
                  <tr>
                    <td><%= resource.name %></td>
                    <td><%= resource.full_path %></td>
                    <td><%= resource.description %></td>
                    <td><%= link_to 'Show', resource %> <%= link_to 'Edit', edit_resource_path(resource) %> <%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  </tr>
                <% end %>
                </tbody>
              </table>
            </div>
	        </div>
			    <!-- /.box-body -->
		    </div>
			  <!-- /.box -->
			</div>
		</div>
	</div>
</section>

app/views/resources/new.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>Resource<small>Version 1.0</small></h1>
  <ol class="breadcrumb">
	<li><a href="#"><i class="fa fa-database"></i> Home</a></li>
	<li>Resource</li>
  </ol>
</section>

<!-- Main content -->
<section class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-6">
				<div class="box">
		            <div class="box-header">
    	              <h3 class="box-title">New Resource</h3>
		            </div>
		            <!-- /.box-header -->
		            <div class="box-body">
                        <%= render 'form' %>
                    </div>
			        <!-- /.box-body -->
			     </div>
			     <!-- /.box -->
			</div>
		</div>
    </div>
</section>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>Resource<small>Version 1.0</small></h1>
  <ol class="breadcrumb">
	<li><a href="#"><i class="fa fa-database"></i> Home</a></li>
	<li>Resource</li>
  </ol>
</section>

<p id="notice"><%= notice %></p>
<section class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-6">
				<div class="box">
		      <div class="box-header">
    	      <h3 class="box-title">New Resource</h3>
		      </div>
		      <!-- /.box-header -->
		      <div class="box-body">
            <p>
              <strong>Full path:</strong>
              <%= @resource.full_path %>
            </p>
            <p>
              <strong>Description:</strong>
              <%= @resource.description %>
            </p>
          </div>
			    <!-- /.box-body -->
	      </div>
			  <!-- /.box -->
	    </div>
	  </div>
  </div>
</section>


<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>